server:
  port: 8084
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: hab
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migration: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
  #kafka
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8085
  #security
  security:
    oauth2:
      client:
        client-id: spring-client
        client-secret: JxqtAwWUhHEgRPJF9piCO11oTwb6DfI9
        access-token-uri: http://localhost:9090/realms/spring-uservice/protocol/openid-connect/token


application:
  config:
    inventory-url: http://localhost:9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Actuator end point
management:
  health:
    circuitbreakers.enabled: true  #enalbe health indicators for Resilience4j circuit breakers. It allows you to see the health status of each circuit breaker via the /actuator/health endpoint.
  endpoints.web.exposure.include: '*' # expose all actuator endpoint
  endpoint.health.show-details: always

#Resilinece4j Properties
resilience4j:
  event-consumer-buffer-size: 10  # to store events
  circuitbreaker.instances.inventory:
    registerHealthIndicator: true
    slidingWindowType: COUNT_BASED
    slidingWindowSize: 5
    failureRateThreshold: 50
    waitDurationInOpenState: 5s
    permittedNumberOfCallsInHalfOpenState: 3
    automaticTransitionFromOpenToHalfOpenEnabled: true
    minimum-number-of-calls: 5
  #Resilience4J Timeout Properties
  timelimiter.instances.inventory.timeout-duration: 4s
  #Resilience4J Retry Properties
  retry.instances.inventory:
    max-attempts: 3
    wait-duration: 2s




